export const API_KEY = "keyXm7poannf3il2T";
export const MAX_RECORDS = 30;

export const actionConstants = {
    UPDATE_AUTHENTICATION : "UPDATE_AUTHENTICATION",
    UPDATE_THEME : "UPDATE_THEME",
    UPDATE_MESSAGE : "UPDATE_MESSAGE",
    IS_LOADING : "IS_LOADING",
    FETCH_LIBRARY : "FETCH_LIBRARY",
    FETCH_SEARCH_RESULT : "FETCH_SEARCH_RESULT",
    FETCH_MY_BOOKS : "FETCH_MY_BOOKS",
    UPDATE_USER_INFO : "UPDATE_USER_INFO",
    LOAD_CATEGORIES: "LOAD_CATEGORIES",
    RESET_SEARCH_RESULT: "RESET_SEARCH_RESULT"
}